# frontend/Dockerfile
FROM node:20

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

# Build the Next.js app
RUN npm run build

EXPOSE 3000

# Run optimized Next.js server
CMD ["npm", "start"]
